### ISSUE TITLE
Support for downloading delisted apps

### ISSUE THREAD

**Issue by upintheairsheep** [NyaMisty/ipatool-py#12]
Please add support for downloading delisted apps only available in your purchase list or a family shared purchase list.

**Comment by ViRb3** [comment]
Already possible, just pass the appID (digits) instead of bundleID (text).

**Comment by mig8447** [comment]
I did this and it didn't work, passing the appId makes the program look up for the app in the store and then fails saying ot is not available

**Comment by ViRb3** [comment]
If it says it's not available, then it's not sadly not available. You must have purchased the app before for this method to work, and it does not transfer over to Family Sharing or anything similar.

**Comment by mig8447** [comment]
Hi, yes, I purchased the app previously with my account and I can download it but only from my purchases list, not from the App Store itself. Nevertheless cannot download it using this tool

**Comment by ViRb3** [comment]
Strange, no idea then. It worked for me when I tried it a few months ago.

**Comment by mig8447** [comment]
Would you have by any chance the command that you used back then? It would be a great starting point. Thank you so much for the prompt response

**Comment by ViRb3** [comment]
Sure:
```sh
python3 ipatool-py/main.py --json download -i "$APPID" -e "$APPLE_USERNAME" -p "$APPLE_PASSWORD$APPLE_2FA"
```

**Comment by mig8447** [comment]
Great, thanks, so I tested and debugged the program and it turns out that if you have: the `appId`, and the `appVersionId` you can perform the download bypassing the app listing. I executed the following and it worked on a de-listed app:

```bash
python3 main.py --json download -i "$APP_ID" -c MX -s http://127.0.0.1:9000 --appVerId "$APP_VERID"
```

As of how did I get the APP_VERID in the first place... I did purchace a copy of iMazing and used the library feature to download the most recent version of the app I needed. Then I exported the IPA file and unzipped it, then examined the `iTunesMetadata.plist` file within the IPA and tried with the last item in the values for the `softwareVersionExternalIdentifiers` key in the file (Which turned out to be the latest version)

This way you may be able to recover unlisted apps yourself, of course if you get the IPA in any other way you could also access the `softwareVersionExternalIdentifiers`

**Comment by mig8447** [comment]
Although possible, the apps downloaded like this, for some reason are not authorized to the account so when you add them via iMazing or AirDrop they won't install. Would you know why is it?

**Comment by ViRb3** [comment]
You should definitely be able to download a delisted app without needing `appVersionId`, maybe a recent update to ipatool-py broke this, I last tested before purchase support was added. Anyway, I recommend you to wait for my patches to be upstreamed to https://github.com/majd/ipatool/, since once that's done, it will contain support for delisted apps, and I can guarantee that it works. As for why iMazing fails to install your app, I have no idea, try `ideviceinstaller`.

**Comment by mig8447** [comment]
Ok, after too much testing, and some combination of proxying with [these instructions](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#step-3-create-the-breakpoint) I finally could download the app I was looking for, just to be disappointed by a "Code signature version is no longer supported" error when installing it, which means the old app won't work on my current iOS version, bummer, but at least I got a better understanding about how the process works. Thanks for this program.

**Comment by NyaMisty** [comment]
@ViRb3 Seems that your work is still not integrated into majd/ipatool ?

**Comment by ViRb3** [comment]
Sadly no, some of my changes were rejected and this feature depended on that. For now you can use my fork here: https://github.com/virb3/ipatool

**Comment by NyaMisty** [comment]
@ViRb3 would you like port your feature into my ipatool-py? I'm very open to most feature request :) 
I believe the new ipatool-py has much more functionality than majd/ipatool now :)
Actually I think majd has actually abandon that project?
